name: Build App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            os_short: ubuntu
          - os: windows-latest
            os_short: windows
          - os: macos-latest
            os_short: macos

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y build-essential pkg-config libgtk-3-dev libwebkit2gtk-4.1-dev libglib2.0-dev

      - name: Install Wails CLI
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Get App version
        id: get_version
        run: |
          VERSION=$(jq -r '.version' frontend/package.json)
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Wails app (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
            wails build -tags webkit2_41

      - name: Build Wails app (Windows/macOS)
        if: matrix.os != 'ubuntu-latest'
        run: |
            wails build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: narrabyte-${{ env.APP_VERSION }}-${{ matrix.os_short }}
          path: ./build/bin/*
